<?xml version="1.0" encoding="UTF-8"?>
<testsuites tests="3" failures="1" disabled="0" errors="0" timestamp="2017-02-05T17:19:08" time="139.427" name="AllTests">
  <testsuite name="LinearSolver" tests="1" failures="0" disabled="0" errors="0" time="0.085">
    <testcase name="HandlesLinearSolver" status="run" time="0.085" classname="LinearSolver" />
  </testsuite>
  <testsuite name="ResidualComputation" tests="1" failures="0" disabled="0" errors="0" time="0">
    <testcase name="HandlesResidualComputation" status="run" time="0" classname="ResidualComputation" />
  </testsuite>
  <testsuite name="SquareCavityG35" tests="1" failures="1" disabled="0" errors="0" time="139.342">
    <testcase name="SquareCavityG35" status="run" time="139.342" classname="SquareCavityG35">
      <failure message="unknown file&#x0A;Unknown C++ exception thrown in the test body." type=""><![CDATA[unknown file
Unknown C++ exception thrown in the test body.]]></failure>
    </testcase>
  </testsuite>
</testsuites>
